# Generated by Django 5.2.8 on 2026-08-11 10:12

import django.db.models.deletion
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('_name', the_music_tree_api_kit.field.AppCharField(db_column='name', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_on', models.DateTimeField(null=True)),
                ('_name', the_music_tree_api_kit.field.AppCharField(db_column='name', max_length=255)),
                ('category', the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fixture_app.fixturecategory')),
                ('partner_category', the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_item', to='fixture_app.fixturecategory')),
                ('related_categories', the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(related_name='related_items', to='fixture_app.fixturecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fixturecategory',
            constraint=models.UniqueConstraint(fields=('_name', 'user'), name='unique_fixture_category_name_per_user'),
        ),
    ]
